apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loan-validator-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: http-01-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: external-nginx

  tls:
    - hosts:
        - demo.azanypay.com
      secretName: demo-azanypay-tls

  rules:
    - host: demo.azanypay.com
      http:
        paths:
          # Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loan-validator-portal-service
                port:
                  number: 8080

          # Backend API
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: government-api-service
                port:
                  number: 8081
