apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: progresql-db-and-otel
  namespace: argocd
spec:
  project: default

  # Target your personal branch
  source:
    repoURL: https://github.com/iam-ismaeel/End-to-End-Deployment-of-a-Loan-App-with-Observability.git
    targetRevision: main
    path: k8s_loan_shared

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ""

  # Sync options
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
